#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


touch open.foam

# Copy the mesh from snappyHexMesh  

rm -rf constant/polyMesh

cp -rf \
    ../simpleFoam/constant/polyMesh \
    constant

# Copy decomposeParDict for parallel run
cp ../snappyHexMesh/system/decomposeParDict system/

# Copy initial conditions
cp -rf ../simpleFoam/0.orig/include/initialConditions 0.orig/include/

restore0Dir

#runApplication mapFields ../simpleFoam -sourceTime latestTime -consistent || { echo "Error running mapFields"; exit 1; }

#cp 0.orig/pointDisplacement 0/pointDisplacement

# This reads system/changeDictionaryDict and updates 0/U cleanly
runApplication changeDictionary

runApplication decomposePar || { echo "Error running decomposePar"; exit 1; }

runParallel $(getApplication) || { echo "Error running $(getApplication)"; exit 1; }

runApplication reconstructPar || { echo "Error running reconstructPar"; exit 1; }
